name: Build Project main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install deps
        run: npm install

      - name: Build project
        run: npm run build

      - name: Archive build
        run: |
          mkdir -p .temp
          tar -czf .temp/project-build.tar.gz build

      - name: Upload build via CSP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: .temp/project-build.tar.gz
          target: ${{ secrets.TARGET }}
          strip_components: 1

      - name: Extract files
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ${{ secrets.TARGET }}
            tar -xzf project-build.tar.gz
            rm project-build.tar.gz
            mv build/* ./
            rm -rf build
